### ISSUE TITLE
Allow CF API usage for Third Party Launchers

### ISSUE THREAD

**Issue by Merith-TK** [GeheimagentNr1/EasierSleeping#2]
![image](https://user-images.githubusercontent.com/10422110/173205447-7de9c9d7-841e-4ae0-b4e2-cf5975e5e118.png)
please turn this on so launchers that are not Curseforge/Overwolf can download the mod

![image](https://user-images.githubusercontent.com/10422110/173205467-436d6b45-f6f2-4c09-8430-99299ed990c1.png)

**Comment by GeheimagentNr1** [comment]
I enabled the API usage for all of my mods.

**Comment by Merith-TK** [comment]
Thanks!
