### ISSUE TITLE
Block cat & gift feature

### ISSUE THREAD

**Issue by PCamille** [GeheimagentNr1/EasierSleeping#4]
**Versions**
Minecraft Version: 1.18.2
Minecraft Forge Version: 40.1.67
Mod Version: 2.1.0

**Log files**
N/A

**Describe the bug**
The mod blocks the feature that a tamed cat can give to the player an item when sleeping.

**To Reproduce**
Steps to reproduce the behaviour:
1. Tame a cat (or more).
2. Sleep.
3. Repeat to be sure (70% chance for a tamed cat to give the player a gift).

**Expected behaviour**
A tamed cat should be able to give an item to the player whan they sleep.

**Screenshots**
N/A

**Additional context**
See [wiki](https://minecraft.fandom.com/wiki/Cat#Gifts) to have an explication of the feature.

**Comment by GeheimagentNr1** [comment]
<table><tbody><tr><th>Status:</th><td>Fixed</td></tr><tr><th>Issue type:</th><td>Bug</td></tr><tr><th>Fix type:</th><td>Bugfix</td></tr><tr><th>Fix version:</th><td>2.1.3</td></tr><tr><th>Fix release date:</th><td>10.04.23</td></tr></tbody></table>

**Issue confirmed for:**

*   Minecraft version: 1.18.2  
    Mod version:  2.1.0
*   Minecraft version: 1.19.4  
    Mod version:  2.1.2

**TODOs:**

*   [x] Fix issue for 1.18.2, 1.19.4
