### ISSUE TITLE
Redistribution

### ISSUE THREAD

**Issue by aaronliu0130** [GeheimagentNr1/EasierSleeping#6]
Do modpack authors have the right to redistribute this mod as an override jar, i.e. in Modrinth modpacks? Alternatively, would you like to release on Modrinth or GitHub?

Additional context: Curseforge does not allow downloading mods from curseforge for modrinth modpacks. So when your mod is not available for download elsewhere, the only option is to redistribute the mod's `.jar` file inside the modpack and move the files to the `mods` directory. Manually moving files like this in a modpack is called overriding.

**Comment by GeheimagentNr1** [comment]
Isn't it possible for Modrinth possible to download the mod via the CurseForge API?  
Because all of my mods are allowed to be downloaded via the CurseForge API.

**Comment by aaronliu0130** [comment]
Used to, but curseforge stopped them from doing that. https://blog.modrinth.com/p/modpack-changes

**Comment by GeheimagentNr1** [comment]
I will create a project on modrinth (https://modrinth.com/mod/easier-sleeping), which is currently under review.
I have uploaded, versions of the mod for Minecraft 1.17.1, 1.18.2 and 1.19.4.
If you need a version for another version of Minecraft, please tell me.

**Comment by aaronliu0130** [comment]
Sounds good!

Cheers,
Aᴀʀᴏɴ

**Comment by GeheimagentNr1** [comment]
The review is done, and the mod is now available on modrinth.
https://modrinth.com/mod/easier-sleeping
Have fun using it.

**Comment by aaronliu0130** [comment]
Thanks!
