### ISSUE TITLE
Cant sleep though the night

### ISSUE THREAD

**Issue by Dreghert** [GeheimagentNr1/EasierSleeping#8]
### Minecraft Version

1.20.1

### Minecraft Forge Version

47.2.0

### Mod Version

2.1.3

### Describe the bug

Sleeping does not skip the night. Instead, it gives the "Good Morning" message and stands the player up, but with no time passed.

### Expected behavior

Sleeping through the night.

### Steps to reproduce

1. Wait until night
2. Right click on bed
3. Get up immediately, with a "Good Morning" message
4. Wonder why it is still night.

**Comment by GeheimagentNr1** [comment]
The night will not be skipped, if the gamerule "doDaylightCycle" is false.  
Please check the value of the gamerule with "/gamerule doDaylightCycle".

**Comment by ItzDogo** [comment]
I am having the same bug, but /gamerule doDaylightCycle is true for me
